CREATE TABLE auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remote_user_id VARCHAR(36) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    display_name VARCHAR(160),
    auth_provider VARCHAR(40) NOT NULL DEFAULT 'password',
    password_hash VARCHAR(255) NOT NULL,
    created_at_millis BIGINT NOT NULL,
    updated_at_millis BIGINT NOT NULL,
    last_login_at_millis BIGINT
);

CREATE INDEX index_auth_users_email ON auth_users (email);
CREATE INDEX index_auth_users_remote_user_id ON auth_users (remote_user_id);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at_millis BIGINT NOT NULL,
    revoked_at_millis BIGINT,
    replaced_by_token_hash VARCHAR(64),
    created_at_millis BIGINT NOT NULL,
    last_used_at_millis BIGINT,
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES auth_users (id)
        ON DELETE CASCADE
);

CREATE INDEX index_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX index_refresh_tokens_expires_at ON refresh_tokens (expires_at_millis);
